/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import FaceDetector
import org.junit.jupiter.api.Test

class AppTest {
    @Test
    fun appHasAGreeting() {
        val classUnderTest = FaceDetector()
    }
}
